VanHackForum/Controllers/BlogsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using VanHackForum.Models;
using Microsoft.AspNet.Identity;
using System.IO;
using PagedList;
using System.Text.RegularExpressions;

namespace VanHackForum.Controllers
{
    public class BlogsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Blogs
        public ActionResult Index(int? page, string tag)
        {
            int pageSize = 20;
            int pageNumber = page ?? 1;
            List<Blog> allBlogs = new List<Blog>();

            if (!string.IsNullOrWhiteSpace(tag))
            {
                ViewBag.Tag = tag;
                allBlogs = db.Blogs.Include(b => b.CreatedBy).Where(x => x.BlogTags.Contains(tag)).OrderByDescending(x => x.CreatedDateTime).ToList();
            }
            else { allBlogs = db.Blogs.Include(b => b.CreatedBy).OrderByDescending(x => x.CreatedDateTime).ToList(); }

            return View(allBlogs.ToPagedList(pageNumber, pageSize));
        }

        // GET: Blogs/Details/5
        public async Task<ActionResult> Details(String title)
        {
            if (String.IsNullOrWhiteSpace(title))
            { return new HttpStatusCodeResult(HttpStatusCode.BadRequest); }

            Blog blog = await db.Blogs.Include(x => x.Comments).Include(x => x.CreatedBy).Where(x => x.BlogUrl == title && x.Deleted == 0).FirstOrDefaultAsync();

            if (blog == null)
            { return HttpNotFound(); }

            if (blog.Tags != null && blog.Tags.Count > 1)
                ViewBag.RelatedBlogs = getRelatedBlogs(blog.Tags, blog);

            return View(blog);
        }

        private IEnumerable<Blog> getRelatedBlogs(IEnumerable<Tag> blogTags, Blog blog)
        {
            var blogs = new List<Blog>();

            for (int i = 0; i < blogTags.Count(); i++)
            {
                blogs = blogTags.ElementAt(i).BlogPosts.Except(new List<Blog>() { blog }).ToList();

                if (blogs.Count > 4) { break; }
            }
            return blogs.Take(4);
        }

        // GET: Blogs/Create
        [Authorize]
        public ActionResult Create()
        {
            var tagList = db.Tags.Select(x => x.BlogTag).ToList();
            string tags = "";
            tagList.ForEach((x) => tags += x + ", ");
            ViewBag.Tags = tags;
            return View(new Blog());
        }

        // POST: Blogs/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public async Task<ActionResult> Create(Blog blog, HttpPostedFileBase image)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    string title = getBlogTitle(blog);
                    blog.BlogUrl = title;
                    blog.CreatedById = User.Identity.GetUserId();
                    if (blog.BlogTags != null)
                    {
                        sortTags(ref blog);
                    }
                    db.Blogs.Add(blog);
                    blog.ImageName = saveBlogHeader(image);

                    var user = db.Users.Find(blog.CreatedById);
                    if (user.Blogs == null) { user.Blogs = new List<Blog>(); }
                    user.Blogs.Add(blog);

                    db.Entry(user).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { title });
                }
                catch (Exception ex)
                {
                    TempData["ErrorMessage"] = ex.Message;
                }
            }

            return View(blog);
        }

        private string getBlogTitle(Blog blog)
        {
            blog.Title = blog.Title.Trim();
            var title = Regex.Replace(blog.Title, "[+=/]", "");
            title = title.Replace(' ', '_') + "_" + getRandomNumber();
            return title;
        }

        private string getRandomNumber()
        {
            var ticksOnVals = new DateTime(2018, 2, 14).Ticks;
            var diffInTicks = DateTime.Now.Ticks - ticksOnVals;
            return diffInTicks.ToString("x");
        }

        private void sortTags(ref Blog blog)
        {
            blog.Tags = new List<Tag>();
            var tags = blog.BlogTags.Split(new string[] { ",", "\n" }, StringSplitOptions.RemoveEmptyEntries);
            foreach (var item in tags)
            {
                var newTag = item.Trim().ToLower();
                Tag tag = db.Tags.SingleOrDefault(x => x.BlogTag.ToLower() == newTag.ToLower());
                if (tag == null)
                {
                    tag = new Tag() { BlogTag = newTag, CreatedById = User.Identity.GetUserId() };
                    db.Tags.Add(tag);
                }
                blog.Tags.Add(tag);
            }
        }

        private string saveBlogHeader(HttpPostedFileBase BlogImage)
        {
            string headerImage = null;
            if (BlogImage != null && BlogImage.ContentLength > 0 && BlogImage.ContentType.Contains("image"))
            {
                if (BlogImage.ContentLength > 1048576)
                { throw new Exception("Header image too large. Please add a header image less than 1mb in size"); }
                headerImage = Guid.NewGuid().ToString("N") + Path.GetExtension(BlogImage.FileName);
                var folderPath = Server.MapPath("~/Content/Blog/Headers");
                if (Directory.Exists(folderPath)) { }
                else { Directory.CreateDirectory(folderPath); }
                BlogImage.SaveAs(Path.Combine(folderPath, headerImage));
            }
            return headerImage;
        }

        // GET: Blogs/Edit/5
        [Authorize]
        public async Task<ActionResult> Edit(string blogtitle)
        {
            try
            {
                if (blogtitle == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Blog blog = db.Blogs.SingleOrDefault(x => x.BlogUrl == blogtitle);
                if (blog == null)
                {
                    return HttpNotFound();
                }

                var userId = User.Identity.GetUserId();
                if (blog.CreatedById != userId)
                {
                    throw new Exception("Access Denied.");
                }

                var tagList = db.Tags.Select(x => x.BlogTag).ToList();
                string tags = "";
                tagList.ForEach((x) => tags += x + ", ");
                ViewBag.Tags = tags;
                return View("Create", blog);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        // POST: Blogs/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [Authorize]
        [HttpPost]
        [ValidateInput(false)]
        public async Task<ActionResult> Edit(Blog newblog, HttpPostedFileBase image)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var userId = User.Identity.GetUserId();
                    var blog = db.Blogs.Find(newblog.ID);
                    if (blog.CreatedById != userId)
                    {
                        throw new Exception("Access Denied.");
                    }

                    blog.Title = newblog.Title; blog.Content = newblog.Content; blog.BlogTags = newblog.BlogTags;

                    string title = getBlogTitle(blog);
                    blog.BlogUrl = title;
                    sortTags(ref blog);
                    if (image != null)
                    {
                        blog.ImageName = saveBlogHeader(image);
                    }
                    db.Entry(blog).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                    return RedirectToAction("Details", new { title });
                }
                return View("Create", newblog);
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Blogs/Delete/5
        [Authorize]
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Blog blog = await db.Blogs.FindAsync(id);
            if (blog == null)
            {
                return HttpNotFound();
            }
            return View(blog);
        }

        // POST: Blogs/Delete/5
        [Authorize]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                Blog blog = await db.Blogs.FindAsync(id);
                if (blog != null)
                {
                    var userId = User.Identity.GetUserId();
                    if (blog.CreatedById != userId) { throw new Exception("access denied"); }
                    db.Blogs.Remove(blog);
                    await db.SaveChangesAsync();
                }
            }
            catch (Exception ex) { TempData["ErrorMessage"] = ex.Message; }
            return RedirectToAction("Index");
        }

        [HttpPost]

VanHackForum/Views/Blogs/Categories.cshtml
@model IEnumerable<string>

<ul class="list-group">
    @foreach (var tag in Model)
    {
    <li class="list-group-item">
        <a href="@Url.Action("Index", "Blogs", new { tag })">
            @tag
        </a>
    </li>
    }
</ul>

VanHackForum/Views/Blogs/Create.cshtml
@model VanHackForum.Models.Blog

@{
    ViewBag.Title = "New Post";
    string action = Model?.ID == 0 ? "Create" : "Edit";
}

@section headerStyle {
    <style>
        /*form {
            margin: 0 auto;
            min-width: 250px;
            max-width: 100%;
        }*/
    </style>
    <link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
    <link href="css/jquery.tagit.css" rel="stylesheet" type="text/css">
}

<h2>Create Post</h2>

<div class="container" style="padding-left: 10%; padding-right: 10%; margin-top: 5%">

    @using (Html.BeginForm(action, "Blogs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(x => x.ID)

        <div class="form-horizontal">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                <div class="col-xs-12">
                    @Html.TextArea("Title", Model.Title, new { @class = "form-control", placeholder = "Blog Post Title", style = "height: 50px;", id = "blogTitle" })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group" style="margin-bottom: 30px;">
                <div class="col-xs-12" id="img-header" style="background-image: url('@Url.Content("~/Content/Blog/Headers")/@Model.ImageName') ;background-repeat:no-repeat; background-position: center center; background-size: contain; height: 250px;">
                    <div class="form-group-container">
                        <div class="image-upload-container">
                            <input type="file" accept="image/*" name="image" onchange="loadFile(event)" style="display:none" id="file-input" src="@Url.Content("~/Content/Blog/Headers")/@Model.ImageName" />
                            <a href="#" id="file-select" style="outline: none; margin-left: 40%;"><i class="glyphicon glyphicon-camera"></i> Select Header Image</a>
                        </div>
                        <script>
                            var fileSelect = document.getElementById("file-select");
                            var fileElem = document.getElementById("file-input");

                            fileSelect.addEventListener("click", function (e) {
                                if (fileElem) {
                                    fileElem.click();
                                } e.preventDefault();
                            }, false);
                            var loadFile = function (event) {
                                $('#img-header').css('background-image', 'url(' + URL.createObjectURL(event.target.files[0]) + ')');
                            };
                        </script>
                    </div>
                </div>
            </div>*@

            <div class="form-group">
                <div class="row">
                    <div class="col-xs-12">
                        <div class="form-group-container">
                            @Html.TextAreaFor(model => model.Content, new { @class = "form-control blog-detail-content", placeholder = "Content" })
                            @Html.ValidationMessageFor(model => model.Content, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="col-xs-12">
                    <div class="form-group-container" title="category">
                        @Html.Hidden("BlogTags", Model.BlogTags, new { id = "BlogTags"})

                        @Html.TextBox("tagss", Model.BlogTags, new { @class = "form-control", id = "tags-textbox", placeholder = "Category",  title="category" })
                        @Html.ValidationMessageFor(model => model.BlogTags, "", new { @class = "text-danger" })
                        <i class="text-danger">to enter a multi-word category, wrap the words in quote ..... "public health"</i>
                    </div>
                </div>
            </div>

            <div class="form-group" style="margin-top: 25px;">
                <div class="col-md-offset-2 col-md-10">
                    <button type="submit" class="btn btn-default">
                        @action Post
                    </button>
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

</div>

@section Scripts {
    <script>
        (function ($) {
            if (!$.curCSS) {
                $.curCSS = $.css;
            }
        })(jQuery);
    </script>
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/tagit")
    @Scripts.Render("~/bundles/ckeditor")

    <script>
        CKEDITOR_BASEPATH = '@Url.Content("~/Scripts/ckeditor/")';
        CKEDITOR.replace('Content');
        CKFinder.setupCKEditor(null, '@Url.Content("~/Scripts/ckfinder/")');

        tagList();
        var eventTags = $('#tags-textbox');
        var availableeTags = '@ViewBag.Tags'.split(', ')

        eventTags.tagit({
            availableTags: availableeTags,
            autocomplete: {
                delay: 0,
                minLength: 2,
                source: availableeTags
            },
            showAutocompleteOnFocus: true,
            allowDuplicates: false,
                removeConfirmation: true,
                singleField: true,
                singleFieldNode: $('#BlogTags'),
                afterTagAdded: function (evt, ui) {
                    if (!ui.duringInitialization) {
                        tagList();
                    }
                },
                afterTagRemoved: function (evt, ui) {
                    tagList();
                }, 
                tagLimit: 1
            });

        function tagList() {
            var result = '@Model.BlogTags';
            $.each($(".tagit").children(),
                function () { result += ($(this).children('.tagit-label').text() + ','); }
            );
            $('#BlogTags').val(result);
        }
        

    </script>
}

VanHackForum/Views/Blogs/Delete.cshtml
@model VanHackForum.Models.Blog

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Blog</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CreatedBy.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedBy.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedBy.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedBy.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BlogUrl)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BlogUrl)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Content)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Content)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HeaderImage)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.HeaderImage)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CreatedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CreatedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Deleted)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Deleted)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ModifiedDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ModifiedDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Version)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Version)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VanHackForum/Views/Blogs/Details.cshtml
@using Microsoft.AspNet.Identity;
@model VanHackForum.Models.Blog

@{
    ViewBag.Title = "Blog Post";
    var userId = User.Identity.GetUserId();
}

@*<div class="jumbotron" style="background: url('@Url.Content("~/Content/Blog/Headers")/@Model.ImageName') no-repeat 50% 50% /cover rgba(17, 18, 19, .6); height: 300px">
</div>*@

<div class="container">
    <div class="well well-lg">
        <h3>@Model.Title</h3>
        <br />
        <div>
            @Html.Raw(Model.Content)
        </div>
        <br />
        @for (int i = 0; i < Model.Tags.Count; i++)
        {
            var tag = Model.Tags.ElementAtOrDefault(i);

            <a href="@Url.Action("Index", "Blogs", new { tag = tag.BlogTag })" style="border: 1px solid #00ff21; border-radius: 10px; padding:  5px 5px 5px 8px; margin: 2px 5px; text-align: center;">
                @tag.BlogTag
            </a>
        }
        <br />
        <div>
            <blockquote class="" style="margin-top: 15px">
                <strong>
                    @Model.CreatedBy.UserName
                </strong>
                <footer>
                    @Model.CreatedDateTime.ToString("dd-MM-yyyy")
                </footer>

                @if (userId == Model.CreatedById)
                {
                    <a href="@Url.Action("Edit", "Blogs", new { blogtitle = Model.BlogUrl })" class="text-danger" style="">
                        <i class="glyphicon glyphicon-pencil"></i> edit
                    </a>
                }
            </blockquote>
        </div>
    </div>

    <hr />

    <div>
        <h3>Comments</h3>
        <hr />

        @if (Request.IsAuthenticated)
        {
            <div class="row">
                @using (Html.BeginForm("PostComment", "Blogs", FormMethod.Post))
                {
                    @Html.Hidden("blogId", Model.ID)

                    <div class="form-group">
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group-container">
                                    @Html.TextArea("comment", new { @class = "form-control blog-detail-content", placeholder = "Content", required = "required" })
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="form-group" style="margin-top: 15px;">
                        <div class="col-md-10">
                            <input type="submit" value="Post Reply" class="btn btn-default" />
                        </div>
                    </div>
                }
            </div>
        }

        <div id="blog-comments" style="margin-top: 50px;">
            @for (int i = 0; i < Model.Comments.Count; i++)
            {
                var comment = Model.Comments.OrderByDescending(x => x.CreatedDateTime).ElementAtOrDefault(i);

                <div class="panel panel-default">
                    <div class="panel-body">
                        @Html.Raw(comment.Content)
                        <blockquote class="blockquote-reverse pull-right" style="margin-bottom: 0px;">
                            @comment.CreatedBy.UserName
                            <footer>
                                @comment.CreatedDateTime.ToString("dd-MM-yyyy")
                            </footer>

                            @if (userId == comment.CreatedById)
                            {
                                <a href="#" class="text-danger edit-comment-button" data-commentid="@comment.ID" data-comment="@comment.Content" style="">
                                    <i class="glyphicon glyphicon-pencil"></i> edit
                                </a>
                            }
                        </blockquote>
                    </div>
                </div>
            }
        </div>
    </div>

</div>

<br />
<a href="@Url.Action("Index", "Blogs")" class="btn btn-lg btn-info">
    << Go Home
</a>



<div class="modal fade" id="editCommentModal" tabindex="-1" role="dialog" aria-labelledby="editCommentModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Edit Comment</h4>
            </div>
            @using (Html.BeginForm("EditComment", "Blogs", FormMethod.Post))
            {
            <div class="modal-body">
                @Html.Hidden("blogId", Model.ID)
                <input type="hidden" name="commentId" id="commentId" />

                <div class="form-group">
                    <div class="row">
                        <div class="col-xs-12">
                            <div class="form-group-container">
                                @Html.TextArea("editComment", new { @class = "form-control blog-detail-content", placeholder = "Content", required = "required" })
                            </div>
                        </div>
                    </div>
                </div>

            </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
            }
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->



@section Scripts {
    <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/tagit")
    @Scripts.Render("~/bundles/ckeditor")

    <script>
        CKEDITOR_BASEPATH = '@Url.Content("~/Scripts/ckeditor/")';
        CKEDITOR.config.toolbar = [
            ['Bold', 'Italic', '-', 'NumberedList', 'BulletedList', '-', 'Link', 'Unlink', '-', 'About']
        ];
        CKEDITOR.replace('comment', {
            //extraPlugins: 'uicolor',
            height: '80px',
        });
        CKEDITOR.replace('editComment', {
            //extraPlugins: 'uicolor',
            height: '80px',
        });

        CKFinder.setupCKEditor(null, '@Url.Content("~/Scripts/ckfinder/")');

        $(".edit-comment-button").on('click', function (e) {
            var btn = e.target;
            var commentId = $(btn).data('commentid')
            var comment = $(btn).data('comment')

            $("#commentId").val(commentId);
            CKEDITOR.instances.editComment.setData(comment)
            $("#editCommentModal").modal('toggle')
        });
    </script>

}

VanHackForum/Views/Blogs/Index.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<VanHackForum.Models.Blog>

@{
    ViewBag.Title = "Forum";
}

@if (Request.IsAuthenticated)
{
    <a href="@Url.Action("Create", "Blogs")" class="btn btn-success btn-lg" title="Write Post" style="position: absolute; top: 95%; left: 95%; padding: 10px 12px; border-radius: 70%;">
        <i class="glyphicon glyphicon-pencil"></i>
    </a>
}

<div class="jumbotron">
    <h3>
        Posts
        @if(ViewBag.Tag != null)
        {
            <text>
         - <i>(@ViewBag.Tag)</i>
            </text>
        }
    </h3>
</div>

<div class="row">
        @for (var i = 0; i < Model.Count; i++)
    {
        var blog = Model.ElementAtOrDefault(i);
        var height = blog.ImageName == "" ? "150px" : "300px";

        <div class="col-xs-6 col-sm-4 col-md-3">
            <div class="thumbnail">
                @*@if (!string.IsNullOrWhiteSpace(blog.ImageName))
            {
                <a href="@Url.Action("Details", "Blogs", new { title = blog.BlogUrl})">
                    <img src="@Url.Content("~/Content/Blog/Headers")/@blog.ImageName" alt="@blog.Title" class="image img-responsive" style="height: 250px; width: 100%">
                </a>
        }*@
                <div class="caption">
                    <h4>
                        <a href="@Url.Action("Details", "Blogs", new { title = blog.BlogUrl})">
                            @blog.Title
                        </a>
                    </h4>
                    @*<p>
                        @Html.Raw(blog.Content);
                    </p>
                    <br />*@
                    <p>
                        <span class="pull-left">
                            @blog.CreatedBy.UserName
                        </span>
                        <br />
                        <span class="pull-right">
                            @blog.CreatedDateTime.ToString("dd-MM-yyyy")
                        </span>
                    </p>
                    @*<p><a href="#" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>*@
                </div>
            </div>
        </div>
}
</div>

<div style="margin-top: 70px;">
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page, tag = ViewBag.Tag }))
</div>